version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting CodeBuild..."
      - pwd
      - ls -la
      - echo "Installing Serverless v3 globally..."
      - npm install -g serverless@3
      - export PATH=$(npm bin -g):$PATH

  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Switching into server directory..."
      - cd server
      - pwd
      - ls -la

  build:
    commands:
      - echo "Installing dependencies..."
      - npm ci --no-audit --no-fund || npm install --no-audit --no-fund
      - echo "Packaging and Deploying using Serverless..."
      - serverless deploy --stage prod --verbose

  post_build:
    commands:
      - echo "Deployment completed successfully."
      - echo "Listing deployed artifacts..."
      - ls -la .serverless/

artifacts:
  base-directory: server/.serverless
  files:
    - '**/*'
  name: serverless-artifacts
