version: 0.2

phases:
  pre_build:
    commands:
      - "echo Starting CodeBuild..."
      - "pwd"
      - "ls -la"
      - "echo Skipping global Serverless install; using project's local Serverless via npx"

  install:
    runtime-versions:
      nodejs: 20
    commands:
      - "echo Navigating to server directory..."
      - "cd server"
      - "pwd"

  build:
    commands:
      - "echo Installing dependencies..."
      - "ulimit -n 4096 || true"
      - "npm ci"
      - "echo Packaging with local Serverless (npx)..."
      - "npx serverless package --verbose"
      - "echo Package contents:"
      - "ls -la .serverless/"

post_build:
  commands:
    - "echo Build completed successfully"

artifacts:
  base-directory: server/.serverless
  files:
    - '**/*'
  name: serverless-artifacts
