version: 0.2

phases:
  pre_build:
    commands:
      - "echo Starting CodeBuild..."
      - "pwd"
      - "ls -la"
      - "echo Installing Serverless v3..."
      - "npm install -g serverless@3"
      - "export PATH=$(npm bin -g):$PATH"

  install:
    runtime-versions:
      nodejs: 20
    commands:
      - "echo Navigating to server directory..."
      - "# If we're already inside server, keep it; otherwise cd into server if it exists"
      - "if [ \"$(basename \"$PWD\")\" = \"server\" ]; then echo 'Already in server: '$PWD; elif [ -d server ]; then cd server; else echo 'ERROR: server directory not found in source. Current listing:'; ls -la; exit 1; fi"
      - "pwd"

  build:
    commands:
      - "echo Installing dependencies..."
      - "ulimit -n 4096 || true"
      - "echo Ensuring build runs in server/"
      - "if [ \"$(basename \"$PWD\")\" = \"server\" ]; then echo 'Already in server: '$PWD; elif [ -d server ]; then cd server; else echo 'ERROR: server directory not found during build. Current listing:'; ls -la; exit 1; fi"
      - "pwd"
      - "ls -la"
      - "npm ci --no-audit --no-fund"
      - "echo Packaging with global Serverless..."
      - "serverless package --verbose"
      - "echo Package contents:"
      - "ls -la .serverless/"

  post_build:
    commands:
      - "echo Build completed successfully"

artifacts:
  base-directory: server/.serverless
  files:
    - '**/*'
  name: serverless-artifacts
