version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd server
      - npm install

  build:
    commands:
      - echo "Building application..."
      - cd server || true
      - npm run build 2>/dev/null || echo "No build script, skipping..."
      - echo "Creating deployment package..."
      - zip -r deployment.zip . -x "node_modules/mocha/*" "node_modules/supertest/*" "node_modules/nodemon/*" ".git/*" ".env*"
      - echo "Uploading to S3..."
      - aws s3 cp deployment.zip s3://my-lambda-deployments/my-backend-api-$(date +%s).zip
      - echo "Deploying Lambda function..."
      - aws lambda update-function-code --function-name my-backend-api --s3-bucket my-lambda-deployments --s3-key my-backend-api-$(date +%s).zip --region ap-south-1 || echo "Function may not exist yet, creating..."
      - echo "Build and deployment complete!"

artifacts:
  files:
    - server/deployment.zip
  name: backend-artifacts
