version: 0.2

env:
  variables:
    STAGE: "dev"                      # change per pipeline stage if you want
    AWS_REGION: "ap-south-1"          # change to your preferred region

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "Ensure Serverless CLI is available..."
      - npx --no-install serverless --version || npm install -g serverless
  pre_build:
    commands:
      - echo "Pre-build: show AWS identity"
      - aws sts get-caller-identity
  build:
    commands:
      - echo "Running tests (if any)..."
      - npm run test || true
      - echo "Deploying via Serverless Framework"
      - npx serverless deploy --stage $STAGE --region $AWS_REGION --verbose
artifacts:
  files:
    - '**/*'
  discard-paths: no
