version: 0.2

env:
  variables:
    SLS_DEBUG: "false"
phases:
  install:
    commands:
      - echo "Install deps & Serverless"
      - npm ci
      - npm install -g serverless
      - serverless --version
  pre_build:
    commands:
      - echo "Configure AWS credentials (provided by CodeBuild service role)"
  build:
    commands:
      - echo "Running tests (if any)"
      - npm test || true
      - echo "Packaging & deploying with Serverless"
      - serverless deploy --stage $SLS_STAGE --verbose
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
