version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - "echo DEBUG: running from PWD:"
      - "pwd"
      - "ls -la"
      - "echo -> changing into server/ directory"
      - "cd server"
      - "echo Installing Serverless v3..."
      - "npm install -g serverless@3"

  build:
    commands:
      - "echo Installing all dependencies..."
      - "npm install --production=false"
      - "echo Packaging with Serverless..."
      - "serverless package"
      - "zip -r ../../my-backend-api.zip *"

artifacts:
  base-directory: server
  files:
    - ".serverless/**/*"
  name: serverless-artifacts
