version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Serverless v3..."
      - npm install -g serverless@3

  build:
    commands:
      - echo "Installing all dependencies..."
      - npm install --production=false

      - echo "Packaging with Serverless..."
      - serverless package

artifacts:
  files:
    - .serverless/**/*
  name: serverless-artifacts
