version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase starting..."
      - node --version
      - npm --version
      - echo "Installing Serverless v3 globally..."
      - npm install -g serverless@3
      - echo "Configuring AWS credentials for Serverless..."
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --region ap-south-1

  install:
    commands:
      - echo "DEBUG starting install phase PWD"
      - pwd
      - ls -la
      - echo "Changing into server directory"
      - cd server
      - echo "Current directory after cd"
      - pwd
      - echo "Listing files in server directory"
      - ls -la
      - echo "Running npm install..."
      - npm install

  build:
    commands:
      - echo "Build phase starting..."
      - pwd
      - echo "Installing webpack/babel build deps..."
      - npm install --no-audit --no-fund --save-dev webpack-node-externals @babel/core @babel/preset-env babel-loader
      - echo "Increasing file descriptor limit..."
      - ulimit -n 65536 || true
      - echo "Cleaning unnecessary node_modules..."
      - rm -rf node_modules/mocha node_modules/supertest node_modules/nodemon || true
      - rm -rf node_modules/**/*.md node_modules/**/test node_modules/**/tests || true
      - echo "File count:"
      - pwd && find . -type f | wc -l
      - echo "Packaging with Serverless..."
      - serverless package --verbose
      - echo "Deploying to AWS..."
      - serverless deploy --verbose

artifacts:
  base-directory: server
  files:
    - .serverless/**/*
  name: serverless-artifacts
