version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Serverless v4..."
      - npm install -g serverless@4
      - echo "Installing project dependencies..."
      - npm install

  build:
    commands:
      - echo "Packaging with Serverless v4..."
      - serverless package

artifacts:
  files:
    - .serverless//*
  name: serverless-artifacts
