version: 0.2

env:
  variables:
    MONGODB_URI: "mongodb+srv://patnalasrikrishnasai:Login@cluster0.igezekd.mongodb.net/academic_management"
    PORT: "5000"
    VITE_API_URL: "https://main.daqm1aijotilg.amplifyapp.com"
    NODE_ENV: "development"
    JWT_SECRET: "7489da8eefb978a24b4d93e10fe4d269"
    JWT_EXPIRES_IN: "7d"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_USER: "caikiet10@gmail.com"
    EMAIL_PASS: "nqip jcfp xlwz iyme"
    FRONTEND_URL: "http://localhost:8080"
    AWS_S3_BUCKET: "mern-deploy-bucket"
    AWS_REGION: "us-east-1"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r backend.zip . -x "*.git*" "node_modules/*"
artifacts:
  files:
    - backend.zip
