version: 0.2

env:
  variables:
    NODE_ENV: "production"
    FRONTEND_URL: "https://main.daqm1aijotilg.amplifyapp.com"
    MONGODB_URI: "mongodb+srv://username:password@cluster0.mongodb.net/academic_management"
    JWT_SECRET: "7489da8eefb978a24b4d93e10fe4d269"
    JWT_EXPIRES_IN: "7d"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_USER: "caikiet10@gmail.com"
    EMAIL_PASS: "your-email-password"
    AWS_S3_BUCKET: "mern-deploy-bucket"
    PORT: "5000"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo " Installing project dependencies..."
      - npm install      # This installs serverless locally from package.json
  pre_build:
    commands:
      - echo "🧹 Cleaning previous builds (optional)"
      - rm -rf .serverless
  build:
    commands:
      - echo "🚀 Deploying backend to AWS Lambda using Serverless..."
      - npx serverless deploy --stage prod --region ap-south-1 --verbose
artifacts:
  files:
    - serverless.yml
    - package.json
    - package-lock.json
    - server.js
    - config/**
    - middleware/**
    - models/**
    - routes/**
    - utils/**
  discard-paths: no
