version: 0.2

env:
  variables:
    NODE_ENV: "production"
    FRONTEND_URL: "https://main.daqm1aijotilg.amplifyapp.com"
    MONGODB_URI: "mongodb+srv://patnalasrikrishnasai:Login@cluster0.igezekd.mongodb.net/academic_management"
    JWT_SECRET: "7489da8eefb978a24b4d93e10fe4d269"
    JWT_EXPIRES_IN: "7d"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_USER: "caikiet10@gmail.com"
    EMAIL_PASS: "nqip jcfp xlwz iyme"
    AWS_S3_BUCKET: "mern-deploy-bucket"
    PORT: "5000"
    # AWS_REGION is reserved; do not set it here

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing Serverless CLI globally..."
      - npm install -g serverless
      - echo "📦 Installing project dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "🧹 Cleaning previous builds..."
      - rm -rf .serverless
  build:
    commands:
      - echo "🚀 Deploying backend to AWS Lambda using Serverless..."
      - serverless deploy --stage prod --region ap-south-1
artifacts:
  files:
    - serverless.yml
    - package.json
    - server.js
    - server/**/*
  discard-paths: no
