Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: server.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
