version: 0.2

phases:
  pre_build:
    commands:
      - "echo Starting CodeBuild for Serverless deployment..."
      - "echo Current directory:"
      - "pwd"
      - "echo Files in current directory:"
      - "ls -la"
      - "echo Installing Serverless Framework..."
      - "npm install -g serverless@3"

  install:
    runtime-versions:
      nodejs: 22
    commands:
      - "echo DEBUG: running from PWD:"
      - "pwd"
      - "ls -la"
      - "echo -> Navigating to server directory"
      - "cd server || exit 1"
      - "pwd"

  build:
    commands:
      - "echo Installing server dependencies..."
      - "npm install --production=false"
      - "echo Serverless Framework version:"
      - "serverless --version"
      - "echo Packaging with Serverless..."
      - "serverless package --verbose"
      - "echo Package complete"
      - "ls -la .serverless/"

post_build:
  commands:
    - "echo Build completed"

artifacts:
  base-directory: server/.serverless
  files:
    - "**/*"
  name: serverless-artifacts
