version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - "echo DEBUG: running from PWD:"
      - "pwd"
      - "ls -la"
      - "echo -> changing into server/ directory"
      - "cd server"
      - "echo Installing Serverless v3..."
      - "npm install -g serverless@3"

  build:
    commands:
      - "echo Installing all dependencies..."
      - "npm install --production=false"
      - "echo Installing webpack dependencies..."
      - "npm install --save-dev webpack-node-externals @babel/core @babel/preset-env babel-loader"
      - "echo Increasing file descriptor limit..."
      - "ulimit -n 65536 || true"
      - "echo Cleaning unnecessary node_modules..."
      - "rm -rf node_modules/mocha node_modules/supertest node_modules/nodemon || true"
      - "rm -rf node_modules/**/*.md node_modules/**/test node_modules/**/tests || true"
      - "echo Current working directory and file count..."
      - "pwd && find . -type f | wc -l"
      - "echo Packaging with Serverless..."
      - "serverless package --verbose"
      - "echo Deploying to AWS..."
      - "serverless deploy --verbose"

artifacts:
  base-directory: server
  files:
    - ".serverless/**/*"
  name: serverless-artifacts
