version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Serverless v3 globally..."
      - npm install -g serverless@3

      - echo "Installing ALL project dependencies (including dev)..."
      - npm install --production=false

  build:
    commands:
      - echo "Packaging with Serverless v3..."
      - serverless package

artifacts:
  files:
    - .serverless/**/*
  name: serverless-artifacts
