version: 0.2
    # AWS_REGION is reserved; do not set it here
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing Serverless CLI globally..."
      - npm install -g serverless
      - serverless --version
      - echo "📦 Installing project dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "🧹 Cleaning previous builds..."
      - rm -rf .serverless
  build:
    commands:
      - echo "🚀 Deploying backend to AWS Lambda using Serverless..."
      - serverless deploy --stage prod --region ap-south-1 --verbose
artifacts:
  files:
    - serverless.yml
    - package.json
    - server.js
    - server/**/*
  discard-paths: no
