version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Node.js 22..."
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - echo "Installing Serverless v3 globally..."
      - npm install -g serverless@3

  install:
    commands:
      - echo "DEBUG starting install phase PWD"
      - pwd
      - ls -la
      - echo "Changing into server directory"
      - cd server
      - echo "Current directory after cd"
      - pwd
      - echo "Listing files in server directory"
      - ls -la
      - echo "Running npm install..."
      - npm install

  build:
    commands:
      - echo "Build phase starting..."
      - pwd
      - cd server || true
      - echo "Installing webpack/babel build deps..."
      - npm install --no-audit --no-fund --save-dev webpack-node-externals @babel/core @babel/preset-env babel-loader
      - echo "Increasing file descriptor limit..."
      - ulimit -n 65536 || true
      - echo "Cleaning unnecessary node_modules..."
      - rm -rf node_modules/mocha node_modules/supertest node_modules/nodemon || true
      - rm -rf node_modules/**/*.md node_modules/**/test node_modules/**/tests || true
      - echo "File count:"
      - pwd && find . -type f | wc -l
      - echo "Packaging with Serverless..."
      - serverless package --verbose
      - echo "Checking AWS permissions for CloudFormation..."
      - 'STACK_NAME="my-backend-api-prod" && aws cloudformation describe-stacks --stack-name "$STACK_NAME" >/dev/null 2>&1 || (echo "ERROR: cloudformation:DescribeStacks failed for stack $STACK_NAME. Ensure CodeBuild role has cloudformation:DescribeStacks." && exit 1)'
      - echo "Deploying to AWS..."
      - serverless deploy --verbose

artifacts:
  base-directory: server
  files:
    - .serverless/**/*
  name: serverless-artifacts
