version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd backend
      - echo "Installing Serverless v3 globally..."
      - npm install -g serverless@3

      - echo "Installing ALL project dependencies..."
      - npm install --production=false

  build:
    commands:
      - echo "Packaging with Serverless..."
      - serverless package

artifacts:
  files:
    - server/.serverless/**/*
  name: serverless-artifacts
